# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cef01aed25c19800d3f7806b7a846ffc58b65a4bbe65677d08df820b8e36bfbf24a6aa371883325d9ca925bfdb34e25e9aa10cb1289447b13a5d48eb977c9f1c

test:
  secret_key_base: cae5ecd20ccb77df0b342d4146b2804e85fe581be548f5f3b59a697d647d3bc0e3b4d11f5473580daca247d80ed0922b064165094536340a4dc5774bbdf86397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
